module.exports = [
  {
    adult: false,
    backdrop_path: '/dK12GIdhGP6NPGFssK2Fh265jyr.jpg',
    genre_ids: [28, 35, 80, 53],
    id: 512195,
    original_language: 'en',
    original_title: 'Red Notice',
    overview:
      "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
    popularity: 4825.133,
    poster_path: '/lAXONuqg41NwUMuzMiFvicDET9Y.jpg',
    release_date: '2021-11-04',
    title: 'Red Notice',
    video: false,
    vote_average: 6.8,
    vote_count: 1970,
  },
  {
    adult: false,
    backdrop_path: '/vJ3ED2jPblACDqaJPZlbN6T1yjy.jpg',
    genre_ids: [53, 80, 28, 12],
    id: 776821,
    original_language: 'es',
    original_title: 'Las leyes de la frontera',
    overview:
      "Introverted Girona student Nacho meets two delinquents from the city's Chinatown and gets caught up in a summer onslaught of burglaries and hold ups that will change his life.",
    popularity: 1070.972,
    poster_path: '/qrq7sGXraFM6H9OcHFKQTKe8A3f.jpg',
    release_date: '2021-10-08',
    title: 'Outlaws',
    video: false,
    vote_average: 6.8,
    vote_count: 65,
  },
  {
    adult: false,
    backdrop_path: '/5WnfgU7myfqgkbl3CSj7LQeHU0e.jpg',
    genre_ids: [27],
    id: 895001,
    original_language: 'th',
    original_title: 'ปริศนารูหลอน',
    overview:
      'When two siblings stumble on a strange hole in the wall of their grandparents’ house, horrifying incidents reveal sinister secrets about their family.',
    popularity: 1070.132,
    poster_path: '/bPq6x47nEqMZED5PrKelcWWpezM.jpg',
    release_date: '2021-12-02',
    title: 'The Whole Truth',
    video: false,
    vote_average: 6.6,
    vote_count: 41,
  },
  {
    adult: false,
    backdrop_path: '/lNnnhBxQESk0WbUXNeh24Dx8XA7.jpg',
    genre_ids: [53, 18, 80],
    id: 767377,
    original_language: 'hi',
    original_title: 'धमाका',
    overview:
      'When a cynical ex-TV news anchor gets an alarming call on his radio show, he sees a chance for a career comeback — but it may cost his conscience.',
    popularity: 1006.543,
    poster_path: '/KowKEuyWziUtnCYicv6zhzTQIv.jpg',
    release_date: '2021-11-19',
    title: 'Dhamaka',
    video: false,
    vote_average: 6.9,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: '/4EJSMQOM1bZPHvzqAQe87suBxdf.jpg',
    genre_ids: [10752, 36, 18],
    id: 885110,
    original_language: 'en',
    original_title: 'Amina',
    overview:
      "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story.",
    popularity: 1255.799,
    poster_path: '/hMIQiwLpBfTfe3ZbRlNx4225Mgg.jpg',
    release_date: '2021-11-04',
    title: 'Amina',
    video: false,
    vote_average: 6.3,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: '/6A5ugY49ukHmMLaMRwkjaKouzCn.jpg',
    genre_ids: [10749, 35, 18],
    id: 810873,
    original_language: 'en',
    original_title: 'Single All the Way',
    overview:
      'Desperate to avoid his family’s judgment about his perpetual single status, Peter convinces his best friend Nick to join him for the holidays and pretend that they’re now in a relationship. But when Peter’s mother sets him up on a blind date with her handsome trainer James, the plan goes awry.',
    popularity: 1150.081,
    poster_path: '/bfZPNzAwUQZ6FZQi1d136KLr3wl.jpg',
    release_date: '2021-12-02',
    title: 'Single All the Way',
    video: false,
    vote_average: 6.4,
    vote_count: 109,
  },
  {
    adult: false,
    backdrop_path: '/7h5WAPAcUzOWpp2jrwHBB48790j.jpg',
    genre_ids: [16, 28],
    id: 843241,
    original_language: 'ja',
    original_title: '劇場版 七つの大罪 光に呪われし者たち',
    overview:
      'With the help of the "Dragon Sin of Wrath" Meliodas and the worst rebels in history, the Seven Deadly Sins, the "Holy War", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the "Lion Sin of Pride" Escanor\'s life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.',
    popularity: 985.509,
    poster_path: '/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg',
    release_date: '2021-07-02',
    title: 'The Seven Deadly Sins: Cursed by Light',
    video: false,
    vote_average: 8.1,
    vote_count: 244,
  },
  {
    adult: false,
    backdrop_path: '/4JEx2BXhOzuN9pCQcnPSWwCiF0W.jpg',
    genre_ids: [16, 35, 10751],
    id: 785545,
    original_language: 'en',
    original_title: 'Shaun the Sheep: The Flight Before Christmas',
    overview:
      "Shaun's seasonal excitement turns to dismay when a farmhouse raid to get bigger stockings for the flock inadvertently leads to Timmy going missing. Can Shaun get Timmy back before he becomes someone else’s present?",
    popularity: 811.728,
    poster_path: '/1eh6Yv6bAU2ghHxP1zgUlMfaOR3.jpg',
    release_date: '2021-12-03',
    title: 'Shaun the Sheep: The Flight Before Christmas',
    video: false,
    vote_average: 6.9,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: '/odKqOY6VE6C59YAdGHB0b5Havye.jpg',
    genre_ids: [10751, 12, 14],
    id: 615666,
    original_language: 'en',
    original_title: 'A Boy Called Christmas',
    overview:
      'An ordinary young boy called Nikolas sets out on an extraordinary adventure into the snowy north in search of his father who is on a quest to discover the fabled village of the elves, Elfhelm. Taking with him a headstrong reindeer called Blitzen and a loyal pet mouse, Nikolas soon meets his destiny in this magical and endearing story that proves nothing is impossible…',
    popularity: 793.622,
    poster_path: '/1sRejtiHOZGggZd9RcmdqbapLM5.jpg',
    release_date: '2021-11-25',
    title: 'A Boy Called Christmas',
    video: false,
    vote_average: 7.9,
    vote_count: 213,
  },
  {
    adult: false,
    backdrop_path: '/pKgfWzxOpvGV3MQ0kLjLdjKAzUe.jpg',
    genre_ids: [18, 80],
    id: 785538,
    original_language: 'pt',
    original_title: '7 Prisioneiros',
    overview:
      'An impoverished teen seeking to escape the clutches of a human trafficker must weigh living up to his moral code against his struggle to survive.',
    popularity: 879.851,
    poster_path: '/5svMKCGnR6Yvj8wxldvDvgUi0Jk.jpg',
    release_date: '2021-10-22',
    title: '7 Prisoners',
    video: false,
    vote_average: 7.1,
    vote_count: 136,
  },
  {
    adult: false,
    backdrop_path: '/b6UXXuRQL3teEMVKTyae5hTq8ke.jpg',
    genre_ids: [35],
    id: 671043,
    original_language: 'fr',
    original_title: 'Pourris gâtés',
    overview:
      'The billionaire is tired of the whims of his own children and decides to teach them a lesson. He announces to them that he has become bankrupt. Now spoiled teenagers will have to do what they have never done: go to work, learn to love and value life.',
    popularity: 690.051,
    poster_path: '/nW5LHayHlbavYD6XRM9SjKi55uu.jpg',
    release_date: '2021-09-15',
    title: 'Spoiled Brats',
    video: false,
    vote_average: 6.1,
    vote_count: 139,
  },
  {
    adult: false,
    backdrop_path: '/d0mpUFKzoPwF1KsdjHpkkaYSvKm.jpg',
    genre_ids: [37],
    id: 618162,
    original_language: 'en',
    original_title: 'The Harder They Fall',
    overview:
      'Gunning for revenge, outlaw Nat Love saddles up with his gang to take down enemy Rufus Buck, a ruthless crime boss who just got sprung from prison.',
    popularity: 688.126,
    poster_path: '/su9WzL7lwUZPhjH6eZByAYFx2US.jpg',
    release_date: '2021-10-22',
    title: 'The Harder They Fall',
    video: false,
    vote_average: 6.8,
    vote_count: 421,
  },
  {
    adult: false,
    backdrop_path: '/eBGKU0ZLJmxtVtzESTB1mfllX1J.jpg',
    genre_ids: [80, 28, 53],
    id: 630004,
    original_language: 'en',
    original_title: 'The Vault',
    overview:
      "When an engineer learns of a mysterious, impenetrable fortress hidden under The Bank of Spain, he joins a crew of master thieves who plan to steal the legendary lost treasure locked inside while the whole country is distracted by Spain's World Cup Final. With thousands of soccer fans cheering in the streets, and security forces closing in, the crew have just minutes to pull off the score of a lifetime.",
    popularity: 578.445,
    poster_path: '/kWhXubAiIcHW0xn5GThflqaKZqh.jpg',
    release_date: '2021-03-03',
    title: 'The Vault',
    video: false,
    vote_average: 7.1,
    vote_count: 453,
  },
  {
    adult: false,
    backdrop_path: '/mu8RKavbv7Ml48twHQ6XVk7zw8e.jpg',
    genre_ids: [28, 80, 53],
    id: 796499,
    original_language: 'en',
    original_title: 'Army of Thieves',
    overview:
      'A mysterious woman recruits bank teller Ludwig Dieter to lead a group of aspiring thieves on a top-secret heist during the early stages of the zombie apocalypse.',
    popularity: 578.376,
    poster_path: '/iPTZGFmPs7HsXHYxiuxGolihjOH.jpg',
    release_date: '2021-10-27',
    title: 'Army of Thieves',
    video: false,
    vote_average: 6.9,
    vote_count: 879,
  },
  {
    adult: false,
    backdrop_path: '/mR4PeGrxdEoAc1i5kN7Q2lOFAA5.jpg',
    genre_ids: [28, 53, 80],
    id: 574060,
    original_language: 'en',
    original_title: 'Gunpowder Milkshake',
    overview:
      'In her turbulent life as a professional assassin, Sam has no choice but to go rogue to save the life of an innocent 8-year-old girl in the middle of the gang war she has unleashed.',
    popularity: 439.755,
    poster_path: '/56ofGPMOZCwlTjTao5fB7vnGOoj.jpg',
    release_date: '2021-07-14',
    title: 'Gunpowder Milkshake',
    video: false,
    vote_average: 6.5,
    vote_count: 415,
  },
  {
    adult: false,
    backdrop_path: '/p1eneBfZCGbbzicwksOhIaibUwk.jpg',
    genre_ids: [18, 37],
    id: 600583,
    original_language: 'en',
    original_title: 'The Power of the Dog',
    overview:
      "A domineering but charismatic rancher wages a war  of intimidation on his brother's new wife and her teen son, until long-hidden secrets come to light.",
    popularity: 391.498,
    poster_path: '/kEy48iCzGnp0ao1cZbNeWR6yIhC.jpg',
    release_date: '2021-09-13',
    title: 'The Power of the Dog',
    video: false,
    vote_average: 6.6,
    vote_count: 307,
  },
  {
    adult: false,
    backdrop_path: '/yEBBtk1eyZltGgJt8Z2zi3KIvvX.jpg',
    genre_ids: [99],
    id: 689249,
    original_language: 'es',
    original_title: 'La Casa de Papel: el fenómeno',
    overview:
      "A documentary on why 'Money Heist' sparked a wave of enthusiasm around the world for a lovable group of thieves and their professor.",
    popularity: 377.955,
    poster_path: '/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg',
    release_date: '2020-04-03',
    title: 'Money Heist: The Phenomenon',
    video: false,
    vote_average: 7.5,
    vote_count: 913,
  },
  {
    adult: false,
    backdrop_path: '/tf81EFI4hMfflKgc8beIMwhFbu2.jpg',
    genre_ids: [35, 10751, 18],
    id: 32471,
    original_language: 'en',
    original_title: 'Mixtape',
    overview:
      'On the eve of Y2K, orphaned 12-year-old Beverly discovers a broken mixtape crafted by her teen parents. Raised by her grandmother - who struggles talking about her late daughter - Beverly sees the mixtape as a chance to finally learn more about her parents.',
    popularity: 376.918,
    poster_path: '/2fpG1PiHPHdLt8X2e7WAct7EVB7.jpg',
    release_date: '2021-12-03',
    title: 'Mixtape',
    video: false,
    vote_average: 7.6,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: '/mI0Qo7VtgW5siCtQQqNPXIk0Ar6.jpg',
    genre_ids: [16, 28, 18, 878],
    id: 685274,
    original_language: 'ja',
    original_title: '機動戦士ガンダム 閃光のハサウェイ',
    overview:
      "After Char's rebellion, Hathaway Noa leads an insurgency against Earth Federation, but meeting an enemy officer and a mysterious woman alters his fate.",
    popularity: 369.572,
    poster_path: '/6gw8onh4FKsruBA7Oouv01EFxzn.jpg',
    release_date: '2021-06-11',
    title: 'Mobile Suit Gundam Hathaway',
    video: false,
    vote_average: 7.9,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: '/aBoHKFFue7TcjRIvoSdvFaS4Kie.jpg',
    genre_ids: [80, 18],
    id: 716810,
    original_language: 'fi',
    original_title: 'Sorjonen: Muraalimurhat',
    overview:
      "A mural painted with blood is found on the wall of Pasila train station, which depicts Finland's best-known serial killer Lasse Maasalo. The text in the mural, “Making the world a better place”, is linked to a voting circulating in social media, where people can vote for persons that world would be a better place without. Soon the first body is found and Sorjonen must find the person who has named himself as The Judge.",
    popularity: 368.504,
    poster_path: '/jtmfXeeECuYNuKSFUlR61ka94QR.jpg',
    release_date: '2021-10-27',
    title: 'Bordertown: The Mural Murders',
    video: false,
    vote_average: 7.2,
    vote_count: 20,
  },
];
